// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/hsm/Desktop/前端自学项目/hsm-ui-demo/node_modules/dumi/theme-default/slots/Navbar/index.js';
